defaults: &defaults
  #working_directory: ./circleci
  docker:
    - image: circleci/node:8

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build
  # lint:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - run: npm run lint
  deploy-github:
    <<: *defaults
    steps:
    - add_ssh_keys:
        fingerprints:
          - "b9:e6:4c:88:f3:47:93:9c:b8:fa:3b:6c:19:59:7b:43"
      - checkout
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy to GitHub Pages
          command: |
              set -e
              remote=$(git config remote.origin.url)
              
              if [ ! -d "build" ]
              then
                  echo "build folder not found"
                  exit 1
              fi
              
              git config --global user.email $GH_EMAIL 
              git config --global user.name $GH_NAME 
              
              if [ ! -d ".git" ]
              then
                git init
                git remote add --fetch origin "$remote"
              fi
              

              if [ ! -d "node_modules" ]
              then 
                echo "not installed yet"
                npm install
              fi
              npm run deploy
              echo "Finished GitHub pages Deployment!"
  deploy-prod:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy to Production
          command: |
              echo "iooooooo"
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare:
          filters:
            branches:
              only: dev
      # - lint:
      #     requires:
      #       - prepare
      #     filters:
      #       branches:
      #         only: dev
      - build:
          requires:
            - prepare
          filters:
            branches:
              only: dev
      - deploy-github:
          requires:
          - build
          filters:
            branches:
              only: dev
      - deploy-prod:
          type: approval
          requires:
            - build
          filters:
            branches:
              only: dev
